#Description: lwIP IPERF; user_visible: True
include_guard(GLOBAL)
message("middleware_lwip_apps_lwiperf component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/src/apps/lwiperf/lwiperf.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/src/include/lwip/apps
)

#OR Logic component
if(CONFIG_USE_middleware_baremetal) 
    include(middleware_baremetal)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT595S_cm33) 
    include(middleware_freertos-kernel_MIMXRT595S_cm33)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1166_cm7) 
    include(middleware_freertos-kernel_MIMXRT1166_cm7)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1021) 
    include(middleware_freertos-kernel_MIMXRT1021)
endif()
if(CONFIG_USE_middleware_freertos-kernel_LPC54S018) 
    include(middleware_freertos-kernel_LPC54S018)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1024) 
    include(middleware_freertos-kernel_MIMXRT1024)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1052) 
    include(middleware_freertos-kernel_MIMXRT1052)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1176_cm7) 
    include(middleware_freertos-kernel_MIMXRT1176_cm7)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1176_cm4) 
    include(middleware_freertos-kernel_MIMXRT1176_cm4)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1166_cm4) 
    include(middleware_freertos-kernel_MIMXRT1166_cm4)
endif()
if(CONFIG_USE_middleware_freertos-kernel_LPC54S018M) 
    include(middleware_freertos-kernel_LPC54S018M)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1064) 
    include(middleware_freertos-kernel_MIMXRT1064)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT685S_cm33) 
    include(middleware_freertos-kernel_MIMXRT685S_cm33)
endif()
if(CONFIG_USE_middleware_freertos-kernel_MIMXRT1062) 
    include(middleware_freertos-kernel_MIMXRT1062)
endif()
if(CONFIG_USE_middleware_freertos-kernel_LPC54628) 
    include(middleware_freertos-kernel_LPC54628)
endif()

include(middleware_lwip)
